import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mi primer app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <header>
        <Link href={"/home"}>Home</Link>
        <br></br>
        <br></br>
        <Link href={"/about"}>About</Link>
        <br></br>
        <br></br>
        <Link href={"/"}>Volver</Link>
      </header>
      <body>{children}</body>
    </html>
  );
}
