import NavBar from "@/components/Navbar";
import "./global.css";

import Link from "next/link";

export const metadata = {
  title: "Mi primer app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex-row">
        <NavBar></NavBar>
        <main className="container mx-auto h-550 flex justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
